# Generated by Django 5.0 on 2024-04-01 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='company',
        ),
        migrations.AlterField(
            model_name='candidates',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
            preserve_default=False,
        ),
    ]
